version: '3'
services:

  frontend:
    build: 
      context: ./Frontend-React
      args:
        - REACT_APP_BACKEND_GRAPHQL=${REACT_APP_BACKEND_GRAPHQL}
        - REACT_APP_BACKEND_UPLOAD =${REACT_APP_BACKEND_UPLOAD} 
        - REACT_APP_FRONTEND=${REACT_APP_FRONTEND} 

    container_name: Frontend
    ports:
      - 80:80


# GraphQl Server

  backend-graphql:
    build: ./backend/GraphQL-Server
    container_name: graphql-server
    ports:
      - 8080:8080
      #- 8081:8081
  
  
  # Backend Services
  
  backend-chkauth:
    build: ./backend/services/ChkAuth
    container_name: backend-chkauth
    ports:
      - 4007:4007

  backend-getallcomments:
    build: ./backend/services/GetAllComments
    container_name: backend-getallcomments
    ports:
      - 4008:4008

  backend-getusercomments:
    build: ./backend/services/GetUserComments
    container_name: backend-getusercomments
    ports:
      - 4009:4009

  backend-signin:
    build: ./backend/services/SignIn
    container_name: backend-signin
    ports:
      - 4001:4001

  backend-signup:
    build: ./backend/services/SignUp
    container_name: backend-signup
    ports:
      - 4002:4002

  backend-likecomment:
    build: ./backend/services/LikeComment
    container_name: backend-likecomment
    ports:
      - 4003:4003

  backend-replycomment:
    build: ./backend/services/ReplyComment
    container_name: backend-replycomment
    ports:
      - 4004:4004
      
  backend-newcomment:
    build: ./backend/services/NewComment
    container_name: backend-newcomment
    ports:
      - 4005:4005

  backend-updatebio:
    build: ./backend/services/UpdateBio
    container_name: backend-updatebio
    ports:
      - 4006:4006

  # backend-PostFile-Service:
  #   build: ./backend/services/PostFile
  #   container_name: backend-PostFile
  #   ports:
  #     - 4010:4010