version: '3'
services:

  # frontend:
  #   build: 
  #     context: ./frontend-react
  #     args:
  #       - REACT_APP_BACKEND_GRAPHQL=${REACT_APP_BACKEND_GRAPHQL}
  #       - REACT_APP_BACKEND_UPLOAD=${REACT_APP_BACKEND_UPLOAD} 
  #       - REACT_APP_FRONTEND=${REACT_APP_FRONTEND} 

  #   container_name: Frontend
  #   ports:
  #     - 80:80


# GraphQl Server

  backend-graphql:
    build: 
        context: ./backend/graphql-server
        args:
          - HOSTIP=${HOSTIP}
    container_name: graphql-server
    ports:
      - 8080:8080
  
  
  # Backend Services
  
  backend-chkauth:
    build: ./backend/services/ChkAuth
    container_name: backend-chkauth
    ports:
      - 4007:4007

  backend-getallcomments:
    build: ./backend/services/GetAllComments
    container_name: backend-getallcomments
    ports:
      - 4008:4008

  backend-getusercomments:
    build: ./backend/services/GetUserComments
    container_name: backend-getusercomments
    ports:
      - 4009:4009

  # backend-signin:
  #   build: ./backend/services/SignIn
  #   container_name: backend-signin
  #   ports:
  #     - 4001:4001

  # backend-signup:
  #   build: ./backend/services/SignUp
  #   container_name: backend-signup
  #   ports:
  #     - 4002:4002

  backend-likecomment:
    build: 
        context: ./backend/services/LikeComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-likecomment
    ports:
      - 4003:4003

  backend-replycomment:
    build: 
        context: ./backend/services/ReplyComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-replycomment
    ports:
      - 4004:4004
      
  backend-newcomment:
    build: 
        context: ./backend/services/NewComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-newcomment
    ports:
      - 4005:4005

  backend-updatebio:
    build: ./backend/services/UpdateBio
    container_name: backend-updatebio
    ports:
      - 4006:4006

  # backend-postfile-service:
  #    build: ./backend/services/PostFile
  #    container_name: backend-PostFile
  #    ports:
  #      - 4010:4010

  # backend-requestotp:
  #   build: 
  #       context: ./backend/services/RequestOTP
  #       args:
  #         - HOSTIP=${HOSTIP}
  #         - SENDER_EMAIL=${SENDER_EMAIL}
  #   container_name: backend-requestotp
  #   ports:
  #     - 4011:4011
  
  # backend-secureupdate:
  #   build: 
  #       context: ./backend/services/SecureUpdate
  #       args:
  #         - HOSTIP=${HOSTIP}
  #         - SENDER_EMAIL=${SENDER_EMAIL}
  #   container_name: backend-secureupdate
  #   ports:
  #     - 4012:4012