version: '3'
services:

  frontend:
    build: 
      context: ./frontend-react
      args:
        - REACT_APP_BACKEND_GRAPHQL=${REACT_APP_BACKEND_GRAPHQL}
        - REACT_APP_BACKEND_UPLOAD=${REACT_APP_BACKEND_UPLOAD} 
        - REACT_APP_FRONTEND=${REACT_APP_FRONTEND} 

    container_name: Frontend
    ports:
       - 80:80


# GraphQl Server

  backend-graphql:
    build: 
        context: ./backend/graphql-server
        args:
          - HOSTIP=${HOSTIP}
    container_name: graphql-server
    ports:
      - 8080:8080
  
  
  # Backend Services
  
  backend-chkauth:
    build: ./backend/services/ChkAuth
    container_name: backend-chkauth
    ports:
      - 4007:4007

  backend-getposts:
    build: ./backend/services/GetPosts
    container_name: backend-getposts
    ports:
      - 4009:4009

  backend-signin:
    build:  
        context: ./backend/services/SignIn
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-signin
    ports:
      - 4001:4001

  backend-signup:
    build: 
      context: ./backend/services/SignUp
      args:
          - HOSTIP=${HOSTIP}
          - SENDER_EMAIL=${SENDER_EMAIL}
    container_name: backend-signup
    volumes: # for aws credentials ( delte this if you are using role based auth)
      - /home/dev/.aws:/root/.aws
    ports:
      - 4002:4002

  backend-likecomment:
    build: 
        context: ./backend/services/LikeComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-likecomment
    ports:
      - 4003:4003

  backend-replycomment:
    build: 
        context: ./backend/services/ReplyComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-replycomment
    ports:
      - 4004:4004
      
  backend-newcomment:
    build: 
        context: ./backend/services/NewComment
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-newcomment
    ports:
      - 4005:4005


  backend-postfile-service:
     build: ./backend/services/PostFile
     container_name: backend-PostFile
     ports:
       - 4010:4010

  backend-requestotp:
    build: 
        context: ./backend/services/RequestOTP
        args:
          - HOSTIP=${HOSTIP}
          - SENDER_EMAIL=${SENDER_EMAIL}
          - ENABLE_AWS
    container_name: backend-requestotp
    volumes:  # for aws credentials ( delete this if you are using role based auth)
      - /home/dev/.aws:/root/.aws
    ports:
      - 4011:4011
  
  backend-secureupdate:
    build: 
        context: ./backend/services/SecureUpdate
        args:
          - HOSTIP=${HOSTIP}
          - SENDER_EMAIL=${SENDER_EMAIL}
    container_name: backend-secureupdate
    ports:
      - 4012:4012

  backend-follow:
    build: 
        context: ./backend/services/Follow
        args:
          - HOSTIP=${HOSTIP}
    container_name: backend-follow
    ports:
      - 4013:4013