// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: gql.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SocialGrpcClient is the client API for SocialGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialGrpcClient interface {
	Chkauth(ctx context.Context, in *JwtdataInput, opts ...grpc.CallOption) (*Authd, error)
	GetAllComments(ctx context.Context, in *GetComments, opts ...grpc.CallOption) (*MongoFields, error)
	GetUserComments(ctx context.Context, in *GetComments, opts ...grpc.CallOption) (*MongoFields, error)
	SignIn(ctx context.Context, in *UsrsigninInput, opts ...grpc.CallOption) (*Jwtdata, error)
	SignUp(ctx context.Context, in *NewUserDataInput, opts ...grpc.CallOption) (*Jwtdata, error)
	LikeComment(ctx context.Context, in *SendLikeInput, opts ...grpc.CallOption) (*MongoFields, error)
	ReplyComment(ctx context.Context, in *ReplyCommentInput, opts ...grpc.CallOption) (*MongoFields, error)
	NewComment(ctx context.Context, in *SendCmtInput, opts ...grpc.CallOption) (*MongoFields, error)
	// rpc PostFile(Upload) returns (MongoFields) {}
	UpdateBio(ctx context.Context, in *UpdateBioInput, opts ...grpc.CallOption) (*MongoFields, error)
}

type socialGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialGrpcClient(cc grpc.ClientConnInterface) SocialGrpcClient {
	return &socialGrpcClient{cc}
}

func (c *socialGrpcClient) Chkauth(ctx context.Context, in *JwtdataInput, opts ...grpc.CallOption) (*Authd, error) {
	out := new(Authd)
	err := c.cc.Invoke(ctx, "/SocialGrpc/Chkauth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) GetAllComments(ctx context.Context, in *GetComments, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/GetAllComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) GetUserComments(ctx context.Context, in *GetComments, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/GetUserComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) SignIn(ctx context.Context, in *UsrsigninInput, opts ...grpc.CallOption) (*Jwtdata, error) {
	out := new(Jwtdata)
	err := c.cc.Invoke(ctx, "/SocialGrpc/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) SignUp(ctx context.Context, in *NewUserDataInput, opts ...grpc.CallOption) (*Jwtdata, error) {
	out := new(Jwtdata)
	err := c.cc.Invoke(ctx, "/SocialGrpc/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) LikeComment(ctx context.Context, in *SendLikeInput, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/LikeComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) ReplyComment(ctx context.Context, in *ReplyCommentInput, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/ReplyComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) NewComment(ctx context.Context, in *SendCmtInput, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/NewComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGrpcClient) UpdateBio(ctx context.Context, in *UpdateBioInput, opts ...grpc.CallOption) (*MongoFields, error) {
	out := new(MongoFields)
	err := c.cc.Invoke(ctx, "/SocialGrpc/UpdateBio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialGrpcServer is the server API for SocialGrpc service.
// All implementations must embed UnimplementedSocialGrpcServer
// for forward compatibility
type SocialGrpcServer interface {
	Chkauth(context.Context, *JwtdataInput) (*Authd, error)
	GetAllComments(context.Context, *GetComments) (*MongoFields, error)
	GetUserComments(context.Context, *GetComments) (*MongoFields, error)
	SignIn(context.Context, *UsrsigninInput) (*Jwtdata, error)
	SignUp(context.Context, *NewUserDataInput) (*Jwtdata, error)
	LikeComment(context.Context, *SendLikeInput) (*MongoFields, error)
	ReplyComment(context.Context, *ReplyCommentInput) (*MongoFields, error)
	NewComment(context.Context, *SendCmtInput) (*MongoFields, error)
	// rpc PostFile(Upload) returns (MongoFields) {}
	UpdateBio(context.Context, *UpdateBioInput) (*MongoFields, error)
	mustEmbedUnimplementedSocialGrpcServer()
}

// UnimplementedSocialGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedSocialGrpcServer struct {
}

func (UnimplementedSocialGrpcServer) Chkauth(context.Context, *JwtdataInput) (*Authd, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chkauth not implemented")
}
func (UnimplementedSocialGrpcServer) GetAllComments(context.Context, *GetComments) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllComments not implemented")
}
func (UnimplementedSocialGrpcServer) GetUserComments(context.Context, *GetComments) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserComments not implemented")
}
func (UnimplementedSocialGrpcServer) SignIn(context.Context, *UsrsigninInput) (*Jwtdata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedSocialGrpcServer) SignUp(context.Context, *NewUserDataInput) (*Jwtdata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedSocialGrpcServer) LikeComment(context.Context, *SendLikeInput) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedSocialGrpcServer) ReplyComment(context.Context, *ReplyCommentInput) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyComment not implemented")
}
func (UnimplementedSocialGrpcServer) NewComment(context.Context, *SendCmtInput) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewComment not implemented")
}
func (UnimplementedSocialGrpcServer) UpdateBio(context.Context, *UpdateBioInput) (*MongoFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBio not implemented")
}
func (UnimplementedSocialGrpcServer) mustEmbedUnimplementedSocialGrpcServer() {}

// UnsafeSocialGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialGrpcServer will
// result in compilation errors.
type UnsafeSocialGrpcServer interface {
	mustEmbedUnimplementedSocialGrpcServer()
}

func RegisterSocialGrpcServer(s grpc.ServiceRegistrar, srv SocialGrpcServer) {
	s.RegisterService(&SocialGrpc_ServiceDesc, srv)
}

func _SocialGrpc_Chkauth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtdataInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).Chkauth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/Chkauth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).Chkauth(ctx, req.(*JwtdataInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_GetAllComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).GetAllComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/GetAllComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).GetAllComments(ctx, req.(*GetComments))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_GetUserComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).GetUserComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/GetUserComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).GetUserComments(ctx, req.(*GetComments))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrsigninInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).SignIn(ctx, req.(*UsrsigninInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserDataInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).SignUp(ctx, req.(*NewUserDataInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLikeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/LikeComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).LikeComment(ctx, req.(*SendLikeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_ReplyComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyCommentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).ReplyComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/ReplyComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).ReplyComment(ctx, req.(*ReplyCommentInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_NewComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCmtInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).NewComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/NewComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).NewComment(ctx, req.(*SendCmtInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGrpc_UpdateBio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBioInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGrpcServer).UpdateBio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SocialGrpc/UpdateBio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGrpcServer).UpdateBio(ctx, req.(*UpdateBioInput))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialGrpc_ServiceDesc is the grpc.ServiceDesc for SocialGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SocialGrpc",
	HandlerType: (*SocialGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chkauth",
			Handler:    _SocialGrpc_Chkauth_Handler,
		},
		{
			MethodName: "GetAllComments",
			Handler:    _SocialGrpc_GetAllComments_Handler,
		},
		{
			MethodName: "GetUserComments",
			Handler:    _SocialGrpc_GetUserComments_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _SocialGrpc_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _SocialGrpc_SignUp_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _SocialGrpc_LikeComment_Handler,
		},
		{
			MethodName: "ReplyComment",
			Handler:    _SocialGrpc_ReplyComment_Handler,
		},
		{
			MethodName: "NewComment",
			Handler:    _SocialGrpc_NewComment_Handler,
		},
		{
			MethodName: "UpdateBio",
			Handler:    _SocialGrpc_UpdateBio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gql.proto",
}
