// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: model/GetUserComments.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetComments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *GetComments) Reset() {
	*x = GetComments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComments) ProtoMessage() {}

func (x *GetComments) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComments.ProtoReflect.Descriptor instead.
func (*GetComments) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{0}
}

func (x *GetComments) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Authd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthdUser string `protobuf:"bytes,1,opt,name=AuthdUser,proto3" json:"AuthdUser,omitempty"`
}

func (x *Authd) Reset() {
	*x = Authd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authd) ProtoMessage() {}

func (x *Authd) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authd.ProtoReflect.Descriptor instead.
func (*Authd) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{1}
}

func (x *Authd) GetAuthdUser() string {
	if x != nil {
		return x.AuthdUser
	}
	return ""
}

type Claims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *Claims) Reset() {
	*x = Claims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{2}
}

func (x *Claims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserCmts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     string `protobuf:"bytes,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *GetUserCmts) Reset() {
	*x = GetUserCmts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCmts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCmts) ProtoMessage() {}

func (x *GetUserCmts) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCmts.ProtoReflect.Descriptor instead.
func (*GetUserCmts) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserCmts) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetUserCmts) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Jwtdata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *Jwtdata) Reset() {
	*x = Jwtdata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jwtdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwtdata) ProtoMessage() {}

func (x *Jwtdata) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwtdata.ProtoReflect.Descriptor instead.
func (*Jwtdata) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{4}
}

func (x *Jwtdata) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtdataInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *JwtdataInput) Reset() {
	*x = JwtdataInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtdataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtdataInput) ProtoMessage() {}

func (x *JwtdataInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtdataInput.ProtoReflect.Descriptor instead.
func (*JwtdataInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{5}
}

func (x *JwtdataInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Likes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Profpic  string `protobuf:"bytes,2,opt,name=Profpic,proto3" json:"Profpic,omitempty"`
}

func (x *Likes) Reset() {
	*x = Likes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Likes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Likes) ProtoMessage() {}

func (x *Likes) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Likes.ProtoReflect.Descriptor instead.
func (*Likes) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{6}
}

func (x *Likes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Likes) GetProfpic() string {
	if x != nil {
		return x.Profpic
	}
	return ""
}

type ReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	PostID   string `protobuf:"bytes,2,opt,name=PostID,proto3" json:"PostID,omitempty"`
	ReplyID  string `protobuf:"bytes,3,opt,name=ReplyID,proto3" json:"ReplyID,omitempty"`
}

func (x *ReplyData) Reset() {
	*x = ReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyData) ProtoMessage() {}

func (x *ReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyData.ProtoReflect.Descriptor instead.
func (*ReplyData) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReplyData) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *ReplyData) GetReplyID() string {
	if x != nil {
		return x.ReplyID
	}
	return ""
}

type LikedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	PostID   string `protobuf:"bytes,2,opt,name=PostID,proto3" json:"PostID,omitempty"`
}

func (x *LikedData) Reset() {
	*x = LikedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikedData) ProtoMessage() {}

func (x *LikedData) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikedData.ProtoReflect.Descriptor instead.
func (*LikedData) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{8}
}

func (x *LikedData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LikedData) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

type MongoFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string       `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Bio       string       `protobuf:"bytes,2,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Profpic   string       `protobuf:"bytes,3,opt,name=Profpic,proto3" json:"Profpic,omitempty"`
	Photos    []string     `protobuf:"bytes,4,rep,name=Photos,proto3" json:"Photos,omitempty"`
	Following []string     `protobuf:"bytes,5,rep,name=Following,proto3" json:"Following,omitempty"`
	Followers []string     `protobuf:"bytes,6,rep,name=Followers,proto3" json:"Followers,omitempty"`
	Replys    []*ReplyData `protobuf:"bytes,7,rep,name=Replys,proto3" json:"Replys,omitempty"`
	Liked     []*LikedData `protobuf:"bytes,8,rep,name=Liked,proto3" json:"Liked,omitempty"`
	Posts     []*PostData  `protobuf:"bytes,9,rep,name=Posts,proto3" json:"Posts,omitempty"` // int32 LastCommentNum = 10 ;
}

func (x *MongoFields) Reset() {
	*x = MongoFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MongoFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoFields) ProtoMessage() {}

func (x *MongoFields) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoFields.ProtoReflect.Descriptor instead.
func (*MongoFields) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{9}
}

func (x *MongoFields) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MongoFields) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MongoFields) GetProfpic() string {
	if x != nil {
		return x.Profpic
	}
	return ""
}

func (x *MongoFields) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *MongoFields) GetFollowing() []string {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *MongoFields) GetFollowers() []string {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *MongoFields) GetReplys() []*ReplyData {
	if x != nil {
		return x.Replys
	}
	return nil
}

func (x *MongoFields) GetLiked() []*LikedData {
	if x != nil {
		return x.Liked
	}
	return nil
}

func (x *MongoFields) GetPosts() []*PostData {
	if x != nil {
		return x.Posts
	}
	return nil
}

type MsgCmts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Comment  string `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Profpic  string `protobuf:"bytes,4,opt,name=Profpic,proto3" json:"Profpic,omitempty"`
}

func (x *MsgCmts) Reset() {
	*x = MsgCmts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCmts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCmts) ProtoMessage() {}

func (x *MsgCmts) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCmts.ProtoReflect.Descriptor instead.
func (*MsgCmts) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{10}
}

func (x *MsgCmts) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MsgCmts) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MsgCmts) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MsgCmts) GetProfpic() string {
	if x != nil {
		return x.Profpic
	}
	return ""
}

type MutationInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ID   string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *MutationInput) Reset() {
	*x = MutationInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MutationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationInput) ProtoMessage() {}

func (x *MutationInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationInput.ProtoReflect.Descriptor instead.
func (*MutationInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{11}
}

func (x *MutationInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MutationInput) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type NewUserDataInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	DOB         string `protobuf:"bytes,3,opt,name=DOB,proto3" json:"DOB,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Mobile      string `protobuf:"bytes,5,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	OTP_Email   string `protobuf:"bytes,6,opt,name=OTP_Email,json=OTPEmail,proto3" json:"OTP_Email,omitempty"`
	OTP_Mobile  string `protobuf:"bytes,7,opt,name=OTP_Mobile,json=OTPMobile,proto3" json:"OTP_Mobile,omitempty"`
	RequestType string `protobuf:"bytes,8,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
}

func (x *NewUserDataInput) Reset() {
	*x = NewUserDataInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUserDataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserDataInput) ProtoMessage() {}

func (x *NewUserDataInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserDataInput.ProtoReflect.Descriptor instead.
func (*NewUserDataInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{12}
}

func (x *NewUserDataInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewUserDataInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NewUserDataInput) GetDOB() string {
	if x != nil {
		return x.DOB
	}
	return ""
}

func (x *NewUserDataInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewUserDataInput) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *NewUserDataInput) GetOTP_Email() string {
	if x != nil {
		return x.OTP_Email
	}
	return ""
}

func (x *NewUserDataInput) GetOTP_Mobile() string {
	if x != nil {
		return x.OTP_Mobile
	}
	return ""
}

func (x *NewUserDataInput) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

type PostData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username  string     `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	MainCmt   string     `protobuf:"bytes,3,opt,name=MainCmt,proto3" json:"MainCmt,omitempty"`
	TimeStamp int64      `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Comments  []*MsgCmts `protobuf:"bytes,5,rep,name=Comments,proto3" json:"Comments,omitempty"` //    []MsgCmts `bson:"Comments" json:"Comments"`
	Likes     []*Likes   `protobuf:"bytes,6,rep,name=Likes,proto3" json:"Likes,omitempty"`       //   []Likes   `bson:"Likes" json:"Likes"`
}

func (x *PostData) Reset() {
	*x = PostData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostData) ProtoMessage() {}

func (x *PostData) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostData.ProtoReflect.Descriptor instead.
func (*PostData) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{13}
}

func (x *PostData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PostData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PostData) GetMainCmt() string {
	if x != nil {
		return x.MainCmt
	}
	return ""
}

func (x *PostData) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *PostData) GetComments() []*MsgCmts {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *PostData) GetLikes() []*Likes {
	if x != nil {
		return x.Likes
	}
	return nil
}

type ReplyCommentInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorUsername string `protobuf:"bytes,1,opt,name=AuthorUsername,proto3" json:"AuthorUsername,omitempty"`
	ReplyUsername  string `protobuf:"bytes,2,opt,name=ReplyUsername,proto3" json:"ReplyUsername,omitempty"`
	ReplyComment   string `protobuf:"bytes,3,opt,name=ReplyComment,proto3" json:"ReplyComment,omitempty"`
	ReplyProfpic   string `protobuf:"bytes,4,opt,name=ReplyProfpic,proto3" json:"ReplyProfpic,omitempty"`
	PostID         string `protobuf:"bytes,5,opt,name=PostID,proto3" json:"PostID,omitempty"`
	ReturnPage     string `protobuf:"bytes,6,opt,name=ReturnPage,proto3" json:"ReturnPage,omitempty"`
}

func (x *ReplyCommentInput) Reset() {
	*x = ReplyCommentInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyCommentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentInput) ProtoMessage() {}

func (x *ReplyCommentInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentInput.ProtoReflect.Descriptor instead.
func (*ReplyCommentInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{14}
}

func (x *ReplyCommentInput) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *ReplyCommentInput) GetReplyUsername() string {
	if x != nil {
		return x.ReplyUsername
	}
	return ""
}

func (x *ReplyCommentInput) GetReplyComment() string {
	if x != nil {
		return x.ReplyComment
	}
	return ""
}

func (x *ReplyCommentInput) GetReplyProfpic() string {
	if x != nil {
		return x.ReplyProfpic
	}
	return ""
}

func (x *ReplyCommentInput) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *ReplyCommentInput) GetReturnPage() string {
	if x != nil {
		return x.ReturnPage
	}
	return ""
}

type SendCmtInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	SessionUser string `protobuf:"bytes,2,opt,name=SessionUser,proto3" json:"SessionUser,omitempty"`
	MainCmt     string `protobuf:"bytes,3,opt,name=MainCmt,proto3" json:"MainCmt,omitempty"`
	Time        string `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	TimeStamp   int64  `protobuf:"varint,5,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Date        string `protobuf:"bytes,6,opt,name=Date,proto3" json:"Date,omitempty"`
	ReturnPage  string `protobuf:"bytes,7,opt,name=ReturnPage,proto3" json:"ReturnPage,omitempty"`
}

func (x *SendCmtInput) Reset() {
	*x = SendCmtInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmtInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmtInput) ProtoMessage() {}

func (x *SendCmtInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmtInput.ProtoReflect.Descriptor instead.
func (*SendCmtInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{15}
}

func (x *SendCmtInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SendCmtInput) GetSessionUser() string {
	if x != nil {
		return x.SessionUser
	}
	return ""
}

func (x *SendCmtInput) GetMainCmt() string {
	if x != nil {
		return x.MainCmt
	}
	return ""
}

func (x *SendCmtInput) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SendCmtInput) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *SendCmtInput) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SendCmtInput) GetReturnPage() string {
	if x != nil {
		return x.ReturnPage
	}
	return ""
}

type SendLikeInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	LikedBy    string `protobuf:"bytes,2,opt,name=LikedBy,proto3" json:"LikedBy,omitempty"`
	LikeByPic  string `protobuf:"bytes,3,opt,name=LikeByPic,proto3" json:"LikeByPic,omitempty"`
	PostID     string `protobuf:"bytes,4,opt,name=PostID,proto3" json:"PostID,omitempty"`
	ReturnPage string `protobuf:"bytes,5,opt,name=ReturnPage,proto3" json:"ReturnPage,omitempty"`
}

func (x *SendLikeInput) Reset() {
	*x = SendLikeInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLikeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLikeInput) ProtoMessage() {}

func (x *SendLikeInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLikeInput.ProtoReflect.Descriptor instead.
func (*SendLikeInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{16}
}

func (x *SendLikeInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SendLikeInput) GetLikedBy() string {
	if x != nil {
		return x.LikedBy
	}
	return ""
}

func (x *SendLikeInput) GetLikeByPic() string {
	if x != nil {
		return x.LikeByPic
	}
	return ""
}

func (x *SendLikeInput) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *SendLikeInput) GetReturnPage() string {
	if x != nil {
		return x.ReturnPage
	}
	return ""
}

type UpdateBioInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Bio      string `protobuf:"bytes,2,opt,name=Bio,proto3" json:"Bio,omitempty"`
}

func (x *UpdateBioInput) Reset() {
	*x = UpdateBioInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBioInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBioInput) ProtoMessage() {}

func (x *UpdateBioInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBioInput.ProtoReflect.Descriptor instead.
func (*UpdateBioInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateBioInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateBioInput) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type Usrsignin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string      `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password       string      `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Email          string      `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Bio            string      `protobuf:"bytes,4,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Photos         []string    `protobuf:"bytes,5,rep,name=Photos,proto3" json:"Photos,omitempty"`
	LastCommentNum int32       `protobuf:"varint,6,opt,name=LastCommentNum,proto3" json:"LastCommentNum,omitempty"`
	Posts          []*PostData `protobuf:"bytes,7,rep,name=Posts,proto3" json:"Posts,omitempty"`
}

func (x *Usrsignin) Reset() {
	*x = Usrsignin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usrsignin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usrsignin) ProtoMessage() {}

func (x *Usrsignin) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usrsignin.ProtoReflect.Descriptor instead.
func (*Usrsignin) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{18}
}

func (x *Usrsignin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Usrsignin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Usrsignin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Usrsignin) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Usrsignin) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Usrsignin) GetLastCommentNum() int32 {
	if x != nil {
		return x.LastCommentNum
	}
	return 0
}

func (x *Usrsignin) GetPosts() []*PostData {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UsrsigninInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *UsrsigninInput) Reset() {
	*x = UsrsigninInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_GetUserComments_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsrsigninInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrsigninInput) ProtoMessage() {}

func (x *UsrsigninInput) ProtoReflect() protoreflect.Message {
	mi := &file_model_GetUserComments_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrsigninInput.ProtoReflect.Descriptor instead.
func (*UsrsigninInput) Descriptor() ([]byte, []int) {
	return file_model_GetUserComments_proto_rawDescGZIP(), []int{19}
}

func (x *UsrsigninInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrsigninInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_model_GetUserComments_proto protoreflect.FileDescriptor

var file_model_GetUserComments_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x05, 0x41, 0x75, 0x74, 0x68,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75, 0x74, 0x68, 0x64, 0x55, 0x73, 0x65, 0x72, 0x22,
	0x24, 0x0a, 0x06, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6d, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x4a, 0x77, 0x74, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x24, 0x0a, 0x0c, 0x4a, 0x77, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x05, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x70, 0x69, 0x63, 0x22, 0x59, 0x0a, 0x09, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x44, 0x22, 0x3f, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x22, 0x90, 0x02, 0x0a, 0x0b, 0x4d, 0x6f, 0x6e, 0x67, 0x6f,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x42, 0x69, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x70, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x69, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x43, 0x6d, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x66, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x72, 0x6f,
	0x66, 0x70, 0x69, 0x63, 0x22, 0x33, 0x0a, 0x0d, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0xe8, 0x01, 0x0a, 0x10, 0x4e, 0x65,
	0x77, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x4f, 0x42, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x4f, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x4f, 0x54, 0x50, 0x5f, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x54, 0x50, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x4f, 0x54, 0x50, 0x5f, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x54, 0x50, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6d, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6d, 0x74,
	0x73, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x52, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x11, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x70, 0x69,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x72,
	0x6f, 0x66, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x22, 0xcc, 0x01,
	0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x61, 0x69, 0x6e, 0x43, 0x6d, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x22, 0x9b, 0x01, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6b, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69,
	0x6b, 0x65, 0x64, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x69, 0x6b,
	0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x50, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x50,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x09, 0x55,
	0x73, 0x72, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73,
	0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x48, 0x0a, 0x0e, 0x55, 0x73, 0x72,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x32, 0x3d, 0x0a, 0x0a, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x70,
	0x63, 0x12, 0x2f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x0c, 0x2e, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_GetUserComments_proto_rawDescOnce sync.Once
	file_model_GetUserComments_proto_rawDescData = file_model_GetUserComments_proto_rawDesc
)

func file_model_GetUserComments_proto_rawDescGZIP() []byte {
	file_model_GetUserComments_proto_rawDescOnce.Do(func() {
		file_model_GetUserComments_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_GetUserComments_proto_rawDescData)
	})
	return file_model_GetUserComments_proto_rawDescData
}

var file_model_GetUserComments_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_model_GetUserComments_proto_goTypes = []interface{}{
	(*GetComments)(nil),       // 0: GetComments
	(*Authd)(nil),             // 1: Authd
	(*Claims)(nil),            // 2: Claims
	(*GetUserCmts)(nil),       // 3: GetUserCmts
	(*Jwtdata)(nil),           // 4: Jwtdata
	(*JwtdataInput)(nil),      // 5: JwtdataInput
	(*Likes)(nil),             // 6: Likes
	(*ReplyData)(nil),         // 7: ReplyData
	(*LikedData)(nil),         // 8: LikedData
	(*MongoFields)(nil),       // 9: MongoFields
	(*MsgCmts)(nil),           // 10: MsgCmts
	(*MutationInput)(nil),     // 11: MutationInput
	(*NewUserDataInput)(nil),  // 12: NewUserDataInput
	(*PostData)(nil),          // 13: PostData
	(*ReplyCommentInput)(nil), // 14: ReplyCommentInput
	(*SendCmtInput)(nil),      // 15: SendCmtInput
	(*SendLikeInput)(nil),     // 16: SendLikeInput
	(*UpdateBioInput)(nil),    // 17: UpdateBioInput
	(*Usrsignin)(nil),         // 18: Usrsignin
	(*UsrsigninInput)(nil),    // 19: UsrsigninInput
}
var file_model_GetUserComments_proto_depIdxs = []int32{
	7,  // 0: MongoFields.Replys:type_name -> ReplyData
	8,  // 1: MongoFields.Liked:type_name -> LikedData
	13, // 2: MongoFields.Posts:type_name -> PostData
	10, // 3: PostData.Comments:type_name -> MsgCmts
	6,  // 4: PostData.Likes:type_name -> Likes
	13, // 5: Usrsignin.Posts:type_name -> PostData
	0,  // 6: SocialGrpc.GetUserComments:input_type -> GetComments
	9,  // 7: SocialGrpc.GetUserComments:output_type -> MongoFields
	7,  // [7:8] is the sub-list for method output_type
	6,  // [6:7] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_model_GetUserComments_proto_init() }
func file_model_GetUserComments_proto_init() {
	if File_model_GetUserComments_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_GetUserComments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCmts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jwtdata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtdataInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Likes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MongoFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCmts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MutationInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUserDataInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyCommentInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmtInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLikeInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBioInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usrsignin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_GetUserComments_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsrsigninInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_GetUserComments_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_GetUserComments_proto_goTypes,
		DependencyIndexes: file_model_GetUserComments_proto_depIdxs,
		MessageInfos:      file_model_GetUserComments_proto_msgTypes,
	}.Build()
	File_model_GetUserComments_proto = out.File
	file_model_GetUserComments_proto_rawDesc = nil
	file_model_GetUserComments_proto_goTypes = nil
	file_model_GetUserComments_proto_depIdxs = nil
}
